services:
  web:
    build: .
    ports:
      - "5050:5050"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    depends_on:
      - db
    environment:
      SECRET_KEY: "replaceinprod"
      DATABASE_URL: "postgresql://postgres:password@db/planning-data-design"
    networks:
      - app-network

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: planning-data-design
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/latest_backup.dump:/docker-entrypoint-initdb.d/latest_backup.dump:ro
      - ./restore-init.sh:/docker-entrypoint-initdb.d/restore-init.sh:ro
    command: ["postgres", "-c", "listen_addresses=*"]
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
