services:
  web:
    build: .
    ports:
      - "5050:5050"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
          ignore:
            - node_modules/
            - .git/
        - action: rebuild
          path: requirements.txt
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      SECRET_KEY: "replaceinprod"
      DATABASE_URL: "postgresql://postgres:password@db/planning-data-design"
      FLASK_DEBUG: 1
      PYTHONDONTWRITEBYTECODE: 1
    networks:
      - app-network

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: planning-data-design
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/latest_backup.dump:/docker-entrypoint-initdb.d/latest_backup.dump:ro
      - ./restore-init.sh:/docker-entrypoint-initdb.d/restore-init.sh:ro
    command: ["postgres", "-c", "listen_addresses=*"]
    networks:
      - app-network

  assets:
    build:
      context: .
      dockerfile: Dockerfile.assets
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - SHELL=/bin/bash
    command: npm run watch
    depends_on:
      - web

  # Optional one-time build service
  assets-build:
    build:
      context: .
      dockerfile: Dockerfile.assets
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run postinstall
    profiles:
      - build

volumes:
  pgdata:
  node_modules: # Persist node_modules to avoid reinstalling on every restart

networks:
  app-network:
    driver: bridge
