"""remove enum values from stage

Revision ID: 0638f26c08da
Revises: b1c0f99b3888
Create Date: 2025-06-17 18:06:06.543908

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '0638f26c08da'
down_revision = 'b1c0f99b3888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.drop_column('prepared_for_platform')
        batch_op.drop_column('ready_for_go_no_go')

    op.sync_enum_values('public', 'stage', ['BACKLOG', 'SCREEN', 'RESEARCH', 'CO_DESIGN', 'TEST_AND_ITERATE', 'ON_THE_PLATFORM', 'ARCHIVED'],
                        [TableReference(table_schema='public', table_name='consideration', column_name='stage'), TableReference(table_schema='public', table_name='question', column_name='stage')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'frequencyofupdates', ['DAILY', 'WEEKLY', 'FORTNIGHTLY', 'MONTHLY', 'EVERY_6_WEEKS', 'QUARTERLY', 'EVERY_6_MONTHS', 'ANNUALLY', 'EVERY_2_YEARS', 'AD_HOC', 'UNKNOWN'],
                        [TableReference(table_schema='public', table_name='consideration', column_name='frequency_of_updates')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'frequencyofupdates', ['DAILY', 'WEEKLY', 'FORTNIGHTLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'AD_HOC', 'EVERY_6_WEEKS', 'EVERY_6_MONTHS', 'EVERY_2_YEARS', 'UNKNOWN'],
                        [TableReference(table_schema='public', table_name='consideration', column_name='frequency_of_updates')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'stage', ['BACKLOG', 'SCREEN', 'RESEARCH', 'CO_DESIGN', 'TEST_AND_ITERATE', 'READY_FOR_GO_NO_GO', 'PREPARED_FOR_PLATFORM', 'ON_THE_PLATFORM', 'ARCHIVED'],
                        [TableReference(table_schema='public', table_name='consideration', column_name='stage'), TableReference(table_schema='public', table_name='question', column_name='stage')],
                        enum_values_to_rename=[])
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ready_for_go_no_go', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('prepared_for_platform', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
