"""one more frequence of updates

Revision ID: 145a88e26dd2
Revises: dc99881d733a
Create Date: 2024-09-06 09:55:03.839470

"""
import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '145a88e26dd2'
down_revision = 'dc99881d733a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'frequencyofupdates', ['DAILY', 'WEEKLY', 'FORTNIGHTLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'AD_HOC', 'EVERY_6_WEEKS', 'EVERY_6_MONTHS', 'EVERY_2_YEARS', 'UNKNOWN'],
                        [TableReference(table_schema='public', table_name='consideration', column_name='frequency_of_updates')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'frequencyofupdates', ['DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'AD_HOC', 'EVERY_6_WEEKS', 'EVERY_6_MONTHS', 'EVERY_2_YEARS', 'UNKNOWN'],
                        [TableReference(table_schema='public', table_name='consideration', column_name='frequency_of_updates')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
