"""add schemas and legislation

Revision ID: 1d6a478b52bc
Revises: 4ba79cc008d9
Create Date: 2024-03-18 13:28:57.076246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d6a478b52bc'
down_revision = '4ba79cc008d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schemas', postgresql.ARRAY(sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('legislation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.drop_column('legislation')
        batch_op.drop_column('schemas')

    # ### end Alembic commands ###
