"""Add python form field

Revision ID: 36380da0dc7b
Revises: fadf7e3f5764
Create Date: 2024-04-22 15:56:20.240445

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "36380da0dc7b"
down_revision = "fadf7e3f5764"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.add_column(sa.Column("python_form", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.drop_column("python_form")

    # ### end Alembic commands ###
