"""add deleted_date field

Revision ID: 38f1ae6961f0
Revises: 1f7f54597a74
Create Date: 2024-03-25 14:42:33.181015

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '38f1ae6961f0'
down_revision = '1f7f54597a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.drop_column('deleted_date')

    # ### end Alembic commands ###
