"""change created to full timestamp

Revision ID: 396535c9bb98
Revises: a37de03e6a59
Create Date: 2024-05-20 13:26:06.712928

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '396535c9bb98'
down_revision = 'a37de03e6a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
