"""add os_declaration field

Revision ID: 415f709f9ac6
Revises: c732726fc3b4
Create Date: 2024-07-17 16:35:27.265534

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '415f709f9ac6'
down_revision = 'c732726fc3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('os_declaration', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.drop_column('os_declaration')

    # ### end Alembic commands ###
