"""add local plan flag

Revision ID: 47b4addc1ded
Revises: 715efa91b9d1
Create Date: 2024-08-20 12:44:01.223905

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '47b4addc1ded'
down_revision = '715efa91b9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_local_plan_data', sa.Boolean()))

    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.execute("UPDATE consideration SET is_local_plan_data = FALSE")
        batch_op.alter_column('is_local_plan_data', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.drop_column('is_local_plan_data')

    # ### end Alembic commands ###
