"""initial migration

Revision ID: 4ba79cc008d9
Revises:
Create Date: 2024-03-18 10:57:26.279886

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ba79cc008d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consideration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('synonyms', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('github_discussion_number', sa.Integer(), nullable=True),
    sa.Column('stage', postgresql.ENUM('BACKLOG', 'SCREEN', 'RESEARCH', 'CO_DESIGN', 'TEST_AND_ITERATE', 'READY_FOR_GO_NO_GO', 'PREPARED_FOR_PLATFORM', 'ON_THE_PLATFORM', 'ARCHIVED', name='stage'), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('expected_number_of_records', sa.Integer(), nullable=True),
    sa.Column('frequency_of_updates', postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'AD_HOC', name='frequencyofupdates'), nullable=True),
    sa.Column('prioritised', sa.Boolean(), nullable=False),
    sa.Column('specification_url', sa.Text(), nullable=True),
    sa.Column('useful_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created', sa.Date(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consideration')
    op.execute('DROP TYPE stage')
    op.execute('DROP TYPE frequencyofupdates')
    # ### end Alembic commands ###
