"""add performance table

Revision ID: 5ce233da822b
Revises: 415f709f9ac6
Create Date: 2024-08-02 13:33:04.324525

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5ce233da822b'
down_revision = '415f709f9ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('considerations', sa.Integer(), nullable=False),
    sa.Column('backlog', sa.Integer(), nullable=False),
    sa.Column('screen', sa.Integer(), nullable=False),
    sa.Column('research', sa.Integer(), nullable=False),
    sa.Column('co_design', sa.Integer(), nullable=False),
    sa.Column('test_and_iterate', sa.Integer(), nullable=False),
    sa.Column('ready_for_go_no_go', sa.Integer(), nullable=False),
    sa.Column('prepared_for_platform', sa.Integer(), nullable=False),
    sa.Column('on_the_platform', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance')
    # ### end Alembic commands ###
