"""Add choose-one-or-more to question type enum

Revision ID: 7d785f99a5fb
Revises: 4067fa61131a
Create Date: 2024-04-29 16:37:41.206801

"""
import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '7d785f99a5fb'
down_revision = '4067fa61131a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'questiontype', ['TEXTAREA', 'CHOOSE_ONE_FROM_LIST', 'CHOOSE_ONE_FROM_LIST_OTHER', 'INPUT', 'ADD_TO_A_LIST', 'CHOOSE_MULTIPLE_FROM_LIST'],
                        [TableReference(table_schema='public', table_name='question', column_name='question_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'questiontype', ['TEXTAREA', 'CHOOSE_ONE_FROM_LIST', 'CHOOSE_ONE_FROM_LIST_OTHER', 'INPUT', 'ADD_TO_A_LIST'],
                        [TableReference(table_schema='public', table_name='question', column_name='question_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
