"""migrate schema data

Revision ID: 895642322125
Revises: c732726fc3b4
Create Date: 2024-07-05 11:04:48.621074

"""
from alembic import op
from sqlalchemy.orm.session import Session

from application.models import Consideration

# revision identifiers, used by Alembic.
revision = '895642322125'
down_revision = 'c732726fc3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    for consideration in session.query(Consideration):
        if consideration.datasets is not None:
            datasets = []
            for dataset in consideration.datasets:
                copy = dataset.copy()
                data = {
                    "name": copy["link_text"],
                    "label": None,
                    "schema_url": copy["link_url"],
                    "platform_url": None,
                    "dataset_editor_url": None,
                }
                datasets.append(data)
            consideration.datasets = datasets
            session.add(consideration)
            session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    for consideration in session.query(Consideration):
        if consideration.datasets is not None:
            datasets = []
            for dataset in consideration.datasets:
                copy = dataset.copy()
                data = {
                    "link_text": copy["name"],
                    "link_url": copy["schema_url"],
                }
                datasets.append(data)
            consideration.datasets = datasets
            session.add(consideration)
            session.commit()
    # ### end Alembic commands ###
