"""move changelog to dedicated table

Revision ID: 971e3a61cd16
Revises: 47b4addc1ded
Create Date: 2024-08-22 10:37:58.692666

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '971e3a61cd16'
down_revision = '47b4addc1ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field', sa.Text(), nullable=False),
    sa.Column('change', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('consideration_id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['consideration_id'], ['consideration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_log')
    # ### end Alembic commands ###
