"""question answer model

Revision ID: 9c972e807bd8
Revises: ad44fcfac4d1
Create Date: 2024-04-09 12:08:33.125266

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c972e807bd8'
down_revision = 'ad44fcfac4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('stage', postgresql.ENUM(name='stage', create_type=False), nullable=False),
    sa.Column('question_type', postgresql.ENUM('TEXTAREA', 'CHOOSE_ONE_FROM_LIST', 'CHOOSE_ONE_FROM_LIST_OTHER', 'INPUT', name='questiontype'), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('next', sa.Text(), nullable=True),
    sa.Column('previous', sa.Text(), nullable=True),
    sa.Column('choices', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created', sa.Date(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('answer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('consideration_id', sa.UUID(), nullable=False),
    sa.Column('question_slug', sa.Text(), nullable=False),
    sa.Column('created', sa.Date(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['consideration_id'], ['consideration.id'], ),
    sa.ForeignKeyConstraint(['question_slug'], ['question.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('question')
    op.execute("DROP TYPE questiontype;")
    # ### end Alembic commands ###
