"""add notes to considerations app

Revision ID: a37de03e6a59
Revises: 376575e0c068
Create Date: 2024-05-20 10:27:29.764107

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a37de03e6a59'
down_revision = '376575e0c068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('consideration_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('created', sa.Date(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['consideration_id'], ['consideration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
