"""rename specification_url to specification

Revision ID: ad44fcfac4d1
Revises: fd65e675f100
Create Date: 2024-03-26 14:47:47.742564

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad44fcfac4d1'
down_revision = 'fd65e675f100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specification', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('specification_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specification_url', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('specification')

    # ### end Alembic commands ###
