"""initial migration

Revision ID: d82b796483b7
Revises:
Create Date: 2024-03-15 14:53:22.168326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd82b796483b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consideration",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("synonyms", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("github_discssion_number", sa.Integer(), nullable=True),
        sa.Column(
            "stage",
            postgresql.ENUM(
                "BACKLOG",
                "SCREEN",
                "RESEARCH",
                "CO_DESIGN",
                "TEST_AND_ITERATE",
                "READY_FOR_GO_NO_GO",
                "PREPARED_FOR_PLATFORM",
                "ON_THE_PLATFORM",
                "ARCHIVED",
                name="stage",
            ),
            nullable=False,
        ),
        sa.Column("public", sa.Boolean(), nullable=False),
        sa.Column("expected_number_of_records", sa.Integer(), nullable=True),
        sa.Column(
            "frequency_of_updates",
            postgresql.ENUM(
                "DAILY",
                "WEEKLY",
                "MONTHLY",
                "QUARTERLY",
                "ANNUALLY",
                "AD_HOC",
                name="frequency_of_updates",
            ),
            nullable=True,
        ),
        sa.Column("specification_url", sa.Text(), nullable=True),
        sa.Column("created", sa.Date(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consideration')
    op.execute('DROP TYPE stage')
    op.execute('DROP TYPE frequency_of_updates')
    # ### end Alembic commands ###
