"""add new frequence of updates

Revision ID: dc99881d733a
Revises: 358969fe3651
Create Date: 2024-09-05 10:34:21.999064

"""
import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = 'dc99881d733a'
down_revision = '358969fe3651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'frequencyofupdates', ['DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'AD_HOC', 'EVERY_6_WEEKS', 'EVERY_6_MONTHS', 'EVERY_2_YEARS', 'UNKNOWN'],
                        [TableReference(table_schema='public', table_name='consideration', column_name='frequency_of_updates')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'frequencyofupdates', ['DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'AD_HOC'],
                        [TableReference(table_schema='public', table_name='consideration', column_name='frequency_of_updates')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
