"""add blocked_reason field

Revision ID: dd6ba652acfb
Revises: 396535c9bb98
Create Date: 2024-06-19 12:54:32.657668

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dd6ba652acfb'
down_revision = '396535c9bb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocked_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.drop_column('blocked_reason')

    # ### end Alembic commands ###
