"""store answer itself in json

Revision ID: e4e19a30c8fa
Revises: fadf7e3f5764
Create Date: 2024-04-22 17:05:34.097568

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4e19a30c8fa'
down_revision = 'fadf7e3f5764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
