"""add slug for consideration

Revision ID: f5f983060c64
Revises: 1d6a478b52bc
Create Date: 2024-03-18 14:55:06.935734

"""
from alembic import op
from slugify import slugify
import sqlalchemy as sa
from sqlalchemy.orm.session import Session

from application.models import Consideration


# revision identifiers, used by Alembic.
revision = 'f5f983060c64'
down_revision = '1d6a478b52bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.Text(), nullable=True))

    session = Session(bind=op.get_bind())
    considerations = session.query(Consideration).all()
    for consideration in considerations:
        name = consideration.name.split("(")[0]
        slug = slugify(name)
        consideration.slug = slug
        session.add(consideration)
        session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consideration', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
