"""add to question type enum

Revision ID: fadf7e3f5764
Revises: f36582b03216
Create Date: 2024-04-22 15:41:28.116939

"""
import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = 'fadf7e3f5764'
down_revision = 'f36582b03216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'questiontype', ['TEXTAREA', 'CHOOSE_ONE_FROM_LIST', 'CHOOSE_ONE_FROM_LIST_OTHER', 'INPUT', 'ADD_TO_A_LIST'],
                        [TableReference(table_schema='public', table_name='question', column_name='question_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'questiontype', ['TEXTAREA', 'CHOOSE_ONE_FROM_LIST', 'CHOOSE_ONE_FROM_LIST_OTHER', 'INPUT'],
                        [TableReference(table_schema='public', table_name='question', column_name='question_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
